### ISSUE TITLE
WTF??

### ISSUE THREAD

**Issue by Mepth** [barneygale/minebnc#1]
At startup, it produces such an error, using Python3 and the last Quarry with pip

https://hastebin.com/dasixefimu.tex

**Comment by barneygale** [comment]
The traceback indicates that the line reads:

```
channels = set(buff.read()).split("\x00")
```

But in the minebnc source it is

```
channels = set(buff.read().split("\x00"))
```

**Comment by Mepth** [comment]
It's still not working, I'm using the latest from github

https://hastebin.com/tecaqoleho.tex

**Comment by barneygale** [comment]
4187cabaad16f81d0cf70a21be8d952d1998f023 may fix this, try latest.

**Comment by Mepth** [comment]
https://hastebin.com/zozesadoro.tex

and

https://hastebin.com/egumewehec.tex

**Comment by barneygale** [comment]
Upgrade quarry to 1.0
